import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";
import { ButtonToggle, LinkButton } from "@/components/Buttons/Buttons";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <header className="w-full flex flex-col gap-10 mt-10 header">
          <div className="flex flex-col self-center gap-5 items-center">
            <svg width="50" height="50" viewBox="0 0 24 24" aria-hidden="true">
              <use href="/clock.svg#clock" />
            </svg>
            <h1 className="text-2xl">Pomodoro - Timer</h1>
          </div>
          <div className="flex gap-5 self-center">
            <LinkButton hrefLink="/" hrefSvg="/home.svg#home"/>
            <LinkButton hrefLink="/" hrefSvg="/history.svg#history"/>
            <LinkButton hrefLink="/" hrefSvg="/settings.svg#settings"/>
            <ButtonToggle />
          </div>
        </header>
        {children}
      </body>
    </html>
  );
}
